(()=>{'use strict';
/* Shared helpers */
window.$=window.$||((s)=>document.querySelector(s));
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata'}).format(new Date());
const toast=(t)=>{let x=document.getElementById('mot-enh-toast');if(!x){x=document.createElement('div');x.id='mot-enh-toast';x.style='position:fixed;left:12px;right:12px;bottom:70px;z-index:99999;background:#303247;color:#fff;padding:12px;border-radius:12px;text-align:center;font:600 13px Poppins,Arial';document.body.appendChild(x)}x.textContent=t;clearTimeout(x._t);x._t=setTimeout(()=>x.remove(),4000)};
/* Larger mobile typography and microphone controls */
const style=document.createElement('style');style.textContent=`.field label{font-size:14px!important}.field input,.field select,.field textarea{font-size:16px!important}.btn{font-size:14px!important}.upload{font-size:14px!important}.checkmain{font-size:14px!important}.na{font-size:13px!important}.rx{font-size:14px!important}.mot-voice-wrap{display:flex;gap:6px;width:100%;align-items:stretch}.mot-voice-wrap>input,.mot-voice-wrap>textarea{flex:1;min-width:0}.mot-mic{width:50px;min-width:50px;border:1px solid #d5dae3;border-radius:10px;background:#fff9df;color:#303247;font-size:21px}.mot-mic.listening{background:#ffc400;box-shadow:0 0 0 3px #ffc40055}@media print{body>*:not(#mot-print-sheet){display:none!important}#mot-print-sheet{display:block!important}}#mot-print-sheet{display:none}`;document.head.appendChild(style);
function installVoice(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return;document.querySelectorAll('input[type=text],input:not([type]),textarea').forEach(f=>{if(f.dataset.voiceReady||f.readOnly||f.disabled)return;f.dataset.voiceReady='1';let w=document.createElement('div');w.className='mot-voice-wrap';f.parentNode.insertBefore(w,f);w.appendChild(f);let b=document.createElement('button');b.type='button';b.className='mot-mic';b.textContent='🎤';b.title='Voice to text';w.appendChild(b);b.onclick=e=>{e.preventDefault();let r=new SR();r.lang=navigator.language||'en-IN';r.interimResults=false;r.continuous=false;r.onstart=()=>{b.textContent='⏹️';b.classList.add('listening')};r.onresult=ev=>{let v=ev.results[0][0].transcript;f.value=(f.value?f.value.trim()+' ':'')+v;f.dispatchEvent(new Event('input',{bubbles:true}));f.dispatchEvent(new Event('change',{bubbles:true}))};r.onerror=ev=>{let m={notallowed:'Microphone permission denied. Allow microphone access.',audio-capture:'No microphone found.',network:'Speech recognition network error. Check internet.',service-not-allowed:'Speech recognition is not allowed.'};toast(m[ev.error]||'Voice recognition failed.')};r.onend=()=>{b.textContent='🎤';b.classList.remove('listening')};try{r.start()}catch(e){toast('Could not start voice recognition. Try again.')}}})}new MutationObserver(installVoice).observe(document.body,{childList:true,subtree:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',installVoice);else installVoice();
/* Done/N/A: selecting N/A disables Done, and vice versa */
document.addEventListener('change',e=>{const t=e.target;if(t?.type!=='checkbox'||!t.checked)return;if(/^done/.test(t.id)){let k=t.id.slice(4),n=document.getElementById('na'+k);if(n){n.checked=false;n.disabled=true}}else if(/^na/.test(t.id)){let k=t.id.slice(2),d=document.getElementById('done'+k);if(d){d.checked=false;d.disabled=true}}},true);
/* Tamil announcement only on explicit click */
window.motAnnounce=(token)=>{if(!('speechSynthesis' in window)){toast('Speech synthesis is not supported on this browser.');return}speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(`தயவு செய்து டோக்கன் எண் ${token} ஐ அணுகவும்`);u.lang='ta-IN';speechSynthesis.speak(u)};
document.addEventListener('click',e=>{let b=e.target.closest?.('[data-announce-token]');if(b){e.preventDefault();window.motAnnounce(b.dataset.announceToken)}},true);
/* System print: full patient record, with photos and requested footer. */
async function getPatient(token){let d=today();try{let s=window.firebase.firestore().collection('minorOT').doc(d).collection('patients').doc(token).get();if((await s).exists){let q=await s;return{id:q.id,...q.data()}}}catch(e){}try{return JSON.parse(localStorage.getItem('mot_'+d)||'[]').find(p=>p.token===token)}catch(e){return null}}
function printSheet(p){let old=document.getElementById('mot-print-sheet');if(old)old.remove();let o=p.otNotes||{};let meds=(p.prescription||[]).map(x=>`<li>${x}</li>`).join('')||'<li>-</li>',adv=(p.instructions||[]).map(x=>`<li>${x}</li>`).join('')||'<li>-</li>';let esc=s=>String(s??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));let q=document.createElement('section');q.id='mot-print-sheet';q.innerHTML=`<div style="font-family:Arial,sans-serif;padding:18mm;color:#111;max-width:210mm"><h2 style="margin:0 0 3mm">${esc(p.name||'Patient')}</h2><div style="font-size:11px;margin-bottom:8mm">${esc(p.date||today())}</div><h3>OT Notes</h3><p>${esc([o.diagnosis,o.procedure,o.site,o.findings,o.details].filter(Boolean).join('\n')||'-').replace(/\n/g,'<br>')}</p><h3>Medications</h3><ul>${meds}</ul><h3>Advice</h3><ul>${adv}</ul><div style="display:flex;gap:8mm;margin-top:8mm">${p.preOpPhoto?`<div><img src="${p.preOpPhoto}" style="width:80mm;max-height:65mm;object-fit:contain"><div>Pre-op Photo</div></div>`:''}${p.postOpPhoto?`<div><img src="${p.postOpPhoto}" style="width:80mm;max-height:65mm;object-fit:contain"><div>Post-op Photo</div></div>`:''}</div><div style="margin-top:12mm;font-size:9pt">IGMC&RI - Department of Surgery</div></div>`;document.body.appendChild(q);window.print();setTimeout(()=>q.remove(),1200)}
async function systemPrint(token){let p=await getPatient(token);if(!p){toast('Patient record not found');return}printSheet(p)}
window.motSystemPrint=systemPrint;
/* Capture existing PDF buttons and turn them into browser/system print buttons. */
document.addEventListener('click',e=>{let b=e.target.closest?.('.pdf');if(!b||!b.dataset.token)return;e.preventDefault();e.stopImmediatePropagation();systemPrint(b.dataset.token)},true);
/* Thermal SEZNIK B21: token number + mandatory footer only. */
(()=>{const S='0000ae30-0000-1000-8000-00805f9b34fb',C='0000ae01-0000-1000-8000-00805f9b34fb';let dev=null,tx=null,busy=false;const crc=a=>{let c=0;for(let v of a){c^=v;for(let i=0;i<8;i++)c=c&128?((c<<1)^7)&255:(c<<1)&255}return c};const pkt=(c,p=[])=>new Uint8Array([81,120,c,0,p.length&255,p.length>>8,...p,crc(p),255]);async function wr(a){for(let i=0;i<a.length;i+=120){let c=a.slice(i,i+120);if(tx.properties.writeWithoutResponse&&tx.writeValueWithoutResponse)await tx.writeValueWithoutResponse(c);else await tx.writeValue(c);await new Promise(r=>setTimeout(r,35))}}async function conn(){if(tx&&dev?.gatt?.connected)return;if(!navigator.bluetooth)throw Error('Bluetooth printing requires Chrome on Android.');dev=await navigator.bluetooth.requestDevice({acceptAllDevices:true,optionalServices:[S]});let ss=await(await dev.gatt.connect()).getPrimaryServices();for(let s of ss){let cs=await s.getCharacteristics().catch(()=>[]);let f=cs.find(x=>x.uuid.toLowerCase()===C&&(x.properties.writeWithoutResponse||x.properties.write));if(f){tx=f;return}}throw Error('Writable B21 channel not found.')}function rows(lines){let W=384,lh=34,p=14,c=document.createElement('canvas');c.width=W;c.height=p+lines.length*lh+p;let x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,W,c.height);x.fillStyle='#000';x.textAlign='center';x.textBaseline='middle';lines.forEach((s,i)=>{x.font=i===0?'bold 34px Arial':'18px Arial';x.fillText(String(s).slice(0,32),W/2,p+17+i*lh)});let a=x.getImageData(0,0,W,c.height).data,o=[];for(let y=0;y<c.height;y++){let r=new Uint8Array(48);for(let q=0;q<W;q++)if(a[(y*W+q)*4]<160)r[q>>3]|=1<<(q&7);o.push(r)}return o}window.motThermalPrint=async token=>{if(busy)return;busy=true;try{await conn();await wr(new Uint8Array([81,120,168,0,1,0,0,0,255,81,120,163,0,1,0,0,0,255]));await wr(pkt(187,[1]));await wr(pkt(164,[51]));await wr(pkt(175,[16,0]));await wr(pkt(190,[0]));for(let r of rows([`TOKEN #${token}`,'IGMC&RI - Department of Surgery']))await wr(pkt(162,[...r]));await wr(pkt(161,[48,0]));toast('Token sent to SEZNIK B21')}catch(e){toast('Thermal print failed: '+e.message)}finally{busy=false}}})();
document.addEventListener('click',e=>{let b=e.target.closest?.('#printToken,.thermal-token,.token-print');if(!b)return;e.preventDefault();e.stopImmediatePropagation();let token=b.dataset.token||document.querySelector('.tokenno')?.textContent?.trim()||'';if(token)window.motThermalPrint(token.replace(/^OT-/i,''))},true);
/* Add explicit buttons to token displays when the page is rendered. */
new MutationObserver(()=>{document.querySelectorAll('.ticket').forEach(t=>{if(t.dataset.enhanced)return;t.dataset.enhanced='1';let token=t.querySelector('.tokenno')?.textContent.trim()||'';let a=document.createElement('div');a.style='display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:10px';a.innerHTML=`<button class="btn yellow" data-announce-token="${token}">🔊 Call Token</button><button class="btn primary token-print" data-token="${token}">🖨 Thermal Token</button>`;t.parentElement.appendChild(a)})}).observe(document.body,{childList:true,subtree:true});
/* Ensure every current record remains in localStorage even when Firebase is available. */
setInterval(()=>{try{let d=today();let c=window.firebase?.firestore()?.collection('minorOT').doc(d).collection('patients');if(!c)return;c.get().then(s=>{if(!s.empty)localStorage.setItem('mot_'+d,JSON.stringify(s.docs.map(x=>({id:x.id,...x.data()}))))}).catch(()=>{})}catch(e){}},15000);
})();