(()=>{'use strict';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const toast=t=>{if(typeof window.toast==='function')return window.toast(t);let x=document.createElement('div');x.textContent=t;x.style='position:fixed;left:12px;right:12px;bottom:70px;z-index:99999;background:#303247;color:#fff;padding:12px;border-radius:12px;text-align:center;font:600 13px Poppins,Arial';document.body.appendChild(x);setTimeout(()=>x.remove(),3000)};
const localKeys=()=>Object.keys(localStorage).filter(k=>/^mot_\d{4}-\d{2}-\d{2}$/.test(k));
function localPatients(){let out=[];for(const k of localKeys()){try{const a=JSON.parse(localStorage.getItem(k)||'[]');if(Array.isArray(a))out.push(...a.map(p=>({...p,date:p.date||k.slice(4)})))}catch(e){}}return out}
async function allPatients(){let map=new Map();localPatients().forEach(p=>{if(p.token)map.set(`${p.date}|${p.token}`,p)});try{if(window.firebase?.apps?.length){const s=await firebase.firestore().collectionGroup('patients').get();s.docs.forEach(d=>{const p={id:d.id,...d.data()};if(p.token)map.set(`${p.date||''}|${p.token}`,p)})}}catch(e){}return [...map.values()]}
function isCompleted(p){return String(p.status||'').toLowerCase()==='completed'||p.completed===true}
async function setCompleted(token,date,value){let key='mot_'+date,a=[];try{a=JSON.parse(localStorage.getItem(key)||'[]')}catch(e){}let p=a.find(x=>x.token===token);if(p){p.status=value?'completed':'pending';p.completed=!!value;localStorage.setItem(key,JSON.stringify(a))}try{if(window.firebase?.apps?.length)await firebase.firestore().collection('minorOT').doc(date).collection('patients').doc(token).update({status:value?'completed':'pending',completed:!!value})}catch(e){}return p}
function injectStyles(){if(document.getElementById('mot-summary-style'))return;let s=document.createElement('style');s.id='mot-summary-style';s.textContent=`.mot-summary-btn{width:100%;margin:10px 0 4px;background:#ffc400;color:#302900;border:0;border-radius:12px;padding:14px;font:700 14px Poppins,Arial}.mot-complete-row{display:flex;gap:8px;margin-top:8px}.mot-complete{flex:1;border:0;border-radius:10px;padding:11px 8px;font:700 12px Poppins,Arial}.mot-complete.pending{background:#20c66a;color:#fff}.mot-complete.completed{background:#f0f2f5;color:#414657}.mot-summary-note{font:500 10px Poppins,Arial;color:#74798a;margin:4px 0 8px}@media print{#mot-summary-print{display:block!important}}#mot-summary-print{display:none}`;document.head.appendChild(s)}
function addRecordsUI(){injectStyles();const h=[...document.querySelectorAll('h2')].find(x=>x.textContent.trim()==='Records');if(!h)return;const card=h.closest('.card');if(!card)return;if(!document.getElementById('motSummaryBtn')){let b=document.createElement('button');b.id='motSummaryBtn';b.className='mot-summary-btn';b.textContent='📊 Print Summary Report';b.onclick=printSummary;h.parentElement?.parentElement?.appendChild(b)}card.querySelectorAll('.patient').forEach(article=>{if(article.querySelector('.mot-complete'))return;const tok=article.querySelector('.token')?.textContent.trim();if(!tok)return;const dp=document.getElementById('datePick');const dt=dp?.value||'';const status=article.querySelector('.push')?.textContent.trim().toLowerCase()==='completed';let row=document.createElement('div');row.className='mot-complete-row';let b=document.createElement('button');b.className='mot-complete '+(status?'completed':'pending');b.textContent=status?'☑ Completed — Mark Pending':'☐ Mark as Completed';b.onclick=async()=>{b.disabled=true;await setCompleted(tok,dt,!status);toast(!status?'Patient marked Completed':'Patient marked Pending');if(typeof window.render==='function')window.render();else addRecordsUI()};row.appendChild(b);article.appendChild(row)})}
function img(src,label){return src?`<div class="sum-photo"><img src="${src}" alt="${esc(label)}"><small>${esc(label)}</small></div>`:''}
function printCss(){return `<style>@page{size:A4;margin:14mm 12mm 16mm}*{box-sizing:border-box}body{margin:0;font-family:Arial,sans-serif;color:#111;background:#fff}.sum-wrap{width:100%;font-size:10.5pt}.sum-title{text-align:center;font-size:17pt;font-weight:700;margin:0 0 2mm}.sum-sub{text-align:center;font-size:9pt;margin-bottom:7mm}.sum-patient{break-inside:avoid;page-break-inside:avoid;border:1px solid #aaa;border-radius:4px;padding:4mm;margin:0 0 5mm}.sum-head{font-size:12pt;font-weight:700;margin-bottom:2mm}.sum-grid{display:grid;grid-template-columns:1fr 1fr;gap:1.5mm 8mm;margin-bottom:3mm}.sum-label{font-weight:700}.sum-section{margin-top:2.5mm}.sum-section b{display:block;margin-bottom:1mm}.sum-section p{margin:0;white-space:pre-wrap}.sum-section ul{margin:1mm 0 0 5mm;padding-left:4mm}.sum-photos{display:flex;gap:8mm;margin-top:3mm}.sum-photo{width:42mm}.sum-photo img{display:block;width:42mm;height:30mm;object-fit:cover;border:1px solid #aaa}.sum-photo small{font-size:8pt}.sum-status{font-weight:700;margin-top:3mm}.sum-footer{position:fixed;bottom:-10mm;left:0;right:0;text-align:center;font-size:8.5pt;border-top:1px solid #bbb;padding-top:2mm} .sum-empty{text-align:center;margin-top:30mm;font-size:12pt}@media print{.sum-footer{display:block}} </style>`}
async function printSummary(){let all=await allPatients();let completed=all.filter(isCompleted).sort((a,b)=>String(a.date||'').localeCompare(String(b.date||''))||String(a.createdAt||'').localeCompare(String(b.createdAt||''))||String(a.token||'').localeCompare(String(b.token||''),undefined,{numeric:true}));if(!completed.length){toast('No completed patients found');return}let old=document.getElementById('mot-summary-print');if(old)old.remove();let body=completed.map((p,i)=>{let o=p.otNotes||{},rx=p.prescription||[],adv=p.instructions||[];return `<article class="sum-patient"><div class="sum-head">${i+1}. ${esc(p.token||'')} — ${esc(p.name||'')}</div><div class="sum-grid"><div><span class="sum-label">Patient Name:</span> ${esc(p.name||'-')}</div><div><span class="sum-label">Token:</span> ${esc(p.token||'-')}</div><div><span class="sum-label">Age/Gender:</span> ${esc(p.age||'-')}/${esc(p.sex||'-')}</div><div><span class="sum-label">Date of Procedure:</span> ${esc(p.date||'-')}</div></div><div class="sum-section"><b>OT Notes</b><p>${esc([o.diagnosis?`Diagnosis: ${o.diagnosis}`:'',o.procedure?`Procedure: ${o.procedure}`:'',o.site?`Site: ${o.site}`:'',o.findings?`Findings: ${o.findings}`:'',o.details?`Details: ${o.details}`:''].filter(Boolean).join('\n')||'-')}</p></div><div class="sum-section"><b>Medications</b>${rx.length?`<ul>${rx.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'<p>-</p>'}</div><div class="sum-section"><b>Advice</b>${adv.length?`<ul>${adv.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'<p>-</p>'}</div>${p.preOpPhoto||p.postOpPhoto?`<div class="sum-section"><b>Photographs</b><div class="sum-photos">${img(p.preOpPhoto,'Pre-op Photo')}${img(p.postOpPhoto,'Post-op Photo')}</div></div>`:''}<div class="sum-status">Status: Completed ☑</div></article>`}).join('');let q=document.createElement('section');q.id='mot-summary-print';q.innerHTML=printCss()+`<div class="sum-wrap"><h1 class="sum-title">IGMC&RI - Department of Surgery - Procedure Summary</h1><div class="sum-sub">Completed patients · ${completed.length} record${completed.length===1?'':'s'} · Chronological order</div>${body}</div><div class="sum-footer">IGMC&RI - Department of Surgery</div>`;document.body.appendChild(q);window.print();setTimeout(()=>q.remove(),1500)}
window.motPrintCompletedSummary=printSummary;
injectStyles();new MutationObserver(()=>addRecordsUI()).observe(document.body,{childList:true,subtree:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',addRecordsUI);else addRecordsUI();
})();